+ fast: `false` (boolean, optional) - Whether or not you want stations in the result to be matched with an id and name according to iRail/Stations.
    By enabling the fast feature, there won't be any matching between station names returned by the NMBS and our database. This results in responses which are a little bit faster. This means there might be differences between the station name in the response and any station name your software knows. Fast is disabled by default, to ensure all stations in the response are matched with an id and a consistent name.
    + Default: false
