# Group Connections

Get routes between two stations, including realtime data on delays.

## Connections API [/connections/{?from,to,date,time,timesel,format,lang,typeOfTransport,alerts,results}]

::: note
#### As of January 20, the following data has been added:
- Intermediate stops are stops where the train will stop, but where the traveller remains seated.
:::

::: note
Alerts are available in the following ways:
- connection: These are all alerts for this connection object. Each alert is unique.
- departure, via departure: These are the alerts for the train which departed
Even though this might duplicate data, this allows anyone to process it easily. Thanks to gzip compression this won't affect the transferred data size.
:::

::: warning
#### <i class="fa fa-warning"></i> Be aware
Trying to query data way in the past, or way in the future, might result in error 500 responses. If you're not sure what causes an error 500 response, be sure to check if your query works for the current day, or if the NMBS website has the data for the date you want to look up.
:::


#### Handling a walking via
In some cases, there might be a walking part in a route. This happens for example when a user arrives in Haren-Zuid and has a next train in Haren, only a few hundred meters further.
- For walking parts, don't attempt to parse train ids or destinations.
- Don't exclude routes which contain walking parts by default, but feel free to give users the option to do so. For example the route Aarschot-Meiser has a small walking part, whereas avoiding that walking part will cause the user to arrive significantly earlier or later.
- Walking parts won't be the first or last part of a route. They can only occur between vias.

+ Parameters

    + from: `Gent-Sint-Pieters` (string, required) - The name or id of the station of departure.

    + to: `Mechelen` (string, required) - The name or id of the destination.

    + timesel: `departure` (enum[string], optional) - Whether the results should show arrivals departures in the station.
        + Default: departure
        + Members
            + departure
            + arrival

    + typeOfTransport: `automatic` (enum[string], optional) - The types of transport to include in the search. Automatic will only allow national (normal) trains for travelling between two stations in Belgium, but will still allow international high speed trains for travel outside Belgium.
        + Default: automatic
        + Members
            + automatic
            + trains
            + nointernationaltrains
            + all

    + alerts: `false`(boolean, optional) - (Deprecated) Whether or not to include alerts about a route in the response. This could be railworks etc, announced on the NMBS website. **Note: alerts are now always included**

    + results: 6 (number, optional) - (Deprecated) The number of results to return. Default value is 6. This might be used as a guideline for the server, but there is no guarantee the server will return this exact amount of results!

    <!-- include(fragments/parameters_time.apib) -->

    <!-- include(fragments/parameters_date.apib) -->

    <!-- include(fragments/parameters_format.apib) -->

    <!-- include(fragments/parameters_lang.apib) -->

### Retrieve connections [GET]

+ Request Json

    + Headers

            Accept: application/json
    
+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body
           
            {
              "version": "1.1",
              "timestamp": "1581855723",
              "connection": [
                {
                  "id": "0",
                  "departure": {
                    "delay": "0",
                    "station": "Oostende",
                    "stationinfo": {
                      "locationX": "2.925809",
                      "locationY": "51.228212",
                      "id": "BE.NMBS.008891702",
                      "name": "Oostende",
                      "@id": "http://irail.be/stations/NMBS/008891702",
                      "standardname": "Oostende"
                    },
                    "time": "1581858540",
                    "vehicle": "BE.NMBS.IC1814",
                    "platform": "6",
                    "platforminfo": {
                      "name": "6",
                      "normal": "0"
                    },
                    "canceled": "0",
                    "stops": {
                      "number": "2",
                      "stop": [
                        {
                          "id": "0",
                          "station": "Brugge",
                          "stationinfo": {
                            "locationX": "3.216726",
                            "locationY": "51.197226",
                            "id": "BE.NMBS.008891009",
                            "name": "Brugge",
                            "@id": "http://irail.be/stations/NMBS/008891009",
                            "standardname": "Brugge"
                          },
                          "scheduledArrivalTime": "1581859380",
                          "arrivalCanceled": "0",
                          "arrived": "0",
                          "arrivalDelay": "0",
                          "scheduledDepartureTime": "1581859500",
                          "departureDelay": "0",
                          "departureCanceled": "0",
                          "left": "0",
                          "isExtraStop": "0",
                          "departureConnection": "http://irail.be/connections/8891009/20200216/IC1814"
                        }
                      ]
                    },
                    "departureConnection": "http://irail.be/connections/8891702/20200216/IC1814",
                    "direction": {
                      "name": "Antwerpen-Centraal"
                    },
                    "left": "0",
                    "walking": "0",
                    "occupancy": {
                      "@id": "http://api.irail.be/terms/unknown",
                      "name": "unknown"
                    }
                  },
                  "arrival": {
                    "delay": "0",
                    "station": "Turnhout",
                    "stationinfo": {
                      "locationX": "4.937415",
                      "locationY": "51.322032",
                      "id": "BE.NMBS.008821907",
                      "name": "Turnhout",
                      "@id": "http://irail.be/stations/NMBS/008821907",
                      "standardname": "Turnhout"
                    },
                    "time": "1581871620",
                    "vehicle": "BE.NMBS.IC4237",
                    "platform": "2",
                    "platforminfo": {
                      "name": "2",
                      "normal": "1"
                    },
                    "canceled": "0",
                    "direction": {
                      "name": "Turnhout"
                    },
                    "arrived": "0",
                    "walking": "0"
                  },
                  "vias": {
                    "number": "1",
                    "via": [
                      {
                        "id": "0",
                        "arrival": {
                          "time": "1581864720",
                          "platform": "10",
                          "platforminfo": {
                            "name": "10",
                            "normal": "1"
                          },
                          "isExtraStop": "0",
                          "delay": "0",
                          "canceled": "0",
                          "arrived": "0",
                          "walking": "0",
                          "direction": {
                            "name": "Antwerpen-Centraal"
                          },
                          "vehicle": "BE.NMBS.IC1814",
                          "departureConnection": "http://irail.be/connections/8821121/20200216/IC1814"
                        },
                        "departure": {
                          "time": "1581867540",
                          "platform": "5",
                          "platforminfo": {
                            "name": "5",
                            "normal": "1"
                          },
                          "isExtraStop": "0",
                          "delay": "0",
                          "canceled": "0",
                          "left": "0",
                          "walking": "0",
                          "direction": {
                            "name": "Turnhout"
                          },
                          "vehicle": "BE.NMBS.IC4237",
                          "stops": {
                            "number": "7",
                            "stop": [
                              {
                                "id": "0",
                                "station": "Mortsel",
                                "stationinfo": {
                                  "locationX": "4.448437",
                                  "locationY": "51.18296",
                                  "id": "BE.NMBS.008821147",
                                  "name": "Mortsel",
                                  "@id": "http://irail.be/stations/NMBS/008821147",
                                  "standardname": "Mortsel"
                                },
                                "scheduledArrivalTime": "1581867720",
                                "arrivalCanceled": "0",
                                "arrived": "0",
                                "arrivalDelay": "0",
                                "scheduledDepartureTime": "1581867780",
                                "departureDelay": "0",
                                "departureCanceled": "0",
                                "left": "0",
                                "isExtraStop": "0",
                                "departureConnection": "http://irail.be/connections/8821147/20200216/IC4237"
                              }
                            ]
                          },
                          "departureConnection": "http://irail.be/connections/8821121/20200216/IC4237",
                          "occupancy": {
                            "@id": "http://api.irail.be/terms/unknown",
                            "name": "unknown"
                          }
                        },
                        "timeBetween": "2820",
                        "station": "Antwerpen-Berchem",
                        "stationinfo": {
                          "locationX": "4.432221",
                          "locationY": "51.19923",
                          "id": "BE.NMBS.008821121",
                          "name": "Antwerpen-Berchem",
                          "@id": "http://irail.be/stations/NMBS/008821121",
                          "standardname": "Antwerpen-Berchem"
                        },
                        "vehicle": "BE.NMBS.IC1814",
                        "direction": {
                          "name": "Antwerpen-Centraal"
                        }
                      }
                    ]
                  },
                  "duration": "13080",
                  "occupancy": {
                    "@id": "http://api.irail.be/terms/unknown",
                    "name": "unknown"
                  }
                }
              ]
            }

    + Attributes (ConnectionResponse)


+ Response 400 (application/json)
            
            {
                "error": 400,
                "message": "to not set. Please review your request and add the right parameters"
            }

+ Response 404 (application/json)

            {
                "error":404,
                "message": "Could not match 'query' with a station id in iRail. Please report this issue at https://github.com/irail/stations/issues/new if you think we should support your query."
            }

+ Response 500 (application/json)
            
            {
                "error": 500,
                "message": "Could not get data. Please report this issue at https://github.com/irail/irail/issues/new"
            }

+ Request XML
    
    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            <connections version="1.1" timestamp="1581855654">
                <connection id="0">
                    <departure delay="0" canceled="0" left="0" walking="0">
                        <station locationX="2.925809" locationY="51.228212" id="BE.NMBS.008891702"
                                 URI="http://irail.be/stations/NMBS/008891702" standardname="Oostende">Oostende
                        </station>
                        <time formatted="2020-02-16T14:09:00">1581858540</time>
                        <vehicle>BE.NMBS.IC1814</vehicle>
                        <platform normal="0">6</platform>
                        <stops number="2">
                            <stop id="0" arrived="0" left="0" isExtraStop="0">
                                <station locationX="3.216726" locationY="51.197226" id="BE.NMBS.008891009"
                                         URI="http://irail.be/stations/NMBS/008891009" standardname="Brugge">Brugge
                                </station>
                                <scheduledArrivalTime formatted="2020-02-16T14:23:00">1581859380</scheduledArrivalTime>
                                <arrivalCanceled>0</arrivalCanceled>
                                <arrivalDelay>0</arrivalDelay>
                                <scheduledDepartureTime formatted="2020-02-16T14:25:00">1581859500</scheduledDepartureTime>
                                <departureDelay>0</departureDelay>
                                <departureCanceled>0</departureCanceled>
                                <departureConnection>http://irail.be/connections/8891009/20200216/IC1814</departureConnection>
                            </stop>
                        </stops>
                        <departureConnection>http://irail.be/connections/8891702/20200216/IC1814</departureConnection>
                        <direction>Antwerpen-Centraal</direction>
                        <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                    </departure>
                    <arrival delay="0" canceled="0" arrived="0" walking="0">
                        <station locationX="4.937415" locationY="51.322032" id="BE.NMBS.008821907"
                                 URI="http://irail.be/stations/NMBS/008821907" standardname="Turnhout">Turnhout
                        </station>
                        <time formatted="2020-02-16T17:47:00">1581871620</time>
                        <vehicle>BE.NMBS.IC4237</vehicle>
                        <platform normal="1">2</platform>
                        <direction>Turnhout</direction>
                    </arrival>
                    <vias number="1">
                        <via id="0">
                            <arrival isExtraStop="0" delay="0" canceled="0" arrived="0" walking="0">
                                <time formatted="2020-02-16T15:52:00">1581864720</time>
                                <platform normal="1">10</platform>
                                <direction>Antwerpen-Centraal</direction>
                                <vehicle>BE.NMBS.IC1814</vehicle>
                                <departureConnection>http://irail.be/connections/8821121/20200216/IC1814</departureConnection>
                            </arrival>
                            <departure isExtraStop="0" delay="0" canceled="0" left="0" walking="0">
                                <time formatted="2020-02-16T16:39:00">1581867540</time>
                                <platform normal="1">5</platform>
                                <direction>Turnhout</direction>
                                <vehicle>BE.NMBS.IC4237</vehicle>
                                <stops number="7">
                                    <stop id="0" arrived="0" left="0" isExtraStop="0">
                                        <station locationX="4.448437" locationY="51.18296" id="BE.NMBS.008821147"
                                                 URI="http://irail.be/stations/NMBS/008821147" standardname="Mortsel">Mortsel
                                        </station>
                                        <scheduledArrivalTime formatted="2020-02-16T16:42:00">1581867720</scheduledArrivalTime>
                                        <arrivalCanceled>0</arrivalCanceled>
                                        <arrivalDelay>0</arrivalDelay>
                                        <scheduledDepartureTime formatted="2020-02-16T16:43:00">1581867780</scheduledDepartureTime>
                                        <departureDelay>0</departureDelay>
                                        <departureCanceled>0</departureCanceled>
                                        <departureConnection>http://irail.be/connections/8821147/20200216/IC4237
                                        </departureConnection>
                                    </stop>
                                </stops>
                                <departureConnection>http://irail.be/connections/8821121/20200216/IC4237</departureConnection>
                                <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                            </departure>
                            <timeBetween>2820</timeBetween>
                            <station locationX="4.432221" locationY="51.19923" id="BE.NMBS.008821121"
                                     URI="http://irail.be/stations/NMBS/008821121" standardname="Antwerpen-Berchem">
                                Antwerpen-Berchem
                            </station>
                            <vehicle>BE.NMBS.IC1814</vehicle>
                            <direction>Antwerpen-Centraal</direction>
                        </via>
                    </vias>
                    <duration>13080</duration>
                    <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                </connection>
            </connections>



+ Response 404 (application/xml)

    + Body
           
            <error code="404">Could not match "samplestation" with a station id in iRail. Please report this issue at https://github.com/irail/stations/issues/new if you think we should support your query.</error>