# Group Connections

Get routes between two stations, including realtime data on delays.

## Connections API [/connections/{?from,to,date,time,timesel,format,lang,fast,typeOfTransport,alerts,results}]

::: warning
#### <i class="fa fa-warning"></i> Be aware
Trying to query data way in the past, or way in the future, might result in error 500 responses. If you're not sure what causes an error 500 response, be sure to check if your query works for the current day, or if the NMBS website has the data for the date you want to look up.
:::

+ Parameters

    + from: `Gent-Sint-Pieters` (string, required) - The name or id of the station of departure.

    + to: `Mechelen` (string, required) - The name or id of the destination.

    + timesel: `departure` (enum[string], optional) - Whether the results should show arrivals departures in the station.
        + Default: departure
        + Members
            + departure
            + arrival

    + typeOfTransport: `trains` (enum[string], optional) - The types of transport to include in the search
        + Default: trains
        + Members
            + trains
            + nointernationaltrains
            + all

    + alerts: `false`(boolean, optional) - Wether or not to include alerts about a route in the response. This could be railworks etc, announced on the NMBS website.

    + results: 6 (number, optional) - The number of results to return. Default value is 6. This might be used as a guideline for the server, but there is no guarantee the server will return this exact amount of results!

    <!-- include(fragments/parameters_time.apib) -->

    <!-- include(fragments/parameters_date.apib) -->    

    <!-- include(fragments/parameters_fast.apib) -->

    <!-- include(fragments/parameters_format.apib) -->

    <!-- include(fragments/parameters_lang.apib) -->

### Retrieve connections [GET]

+ Request Json

    + Headers

            Accept: application/json
    
+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body
           
            {

                "version": "1.1",
                "timestamp": "1506352780",
                "connection": [
                {
                    "id": "0",
                    "departure": {
                        "delay": "0",
                        "station": "Ghent-Sint-Pieters",
                        "stationinfo": {
                            "id": "BE.NMBS.008892007",
                            "locationX": "3.710675",
                            "locationY": "51.035896",
                            "@id": "http://irail.be/stations/NMBS/008892007",
                            "name": "Ghent-Sint-Pieters",
                            "standardname": "Gent-Sint-Pieters"
                        },
                        "time": "1506339600",
                        "vehicle": "BE.NMBS.IC1512",
                        "platform": "11",
                        "platforminfo": {
                            "name": "11",
                            "normal": "1"
                        },
                        "canceled": "0",
                        "direction": {
                            "name": "Genk"
                        },
                        "departureConnection": "http://irail.be/connections/8892007/20170925/IC1512",
                        "occupancy": {
                            "@id": "http://api.irail.be/terms/unknown",
                            "name": "unknown"
                        }
                    },
                    "arrival": {
                        "delay": "420",
                        "station": "Kiewit",
                        "stationinfo": {
                            "id": "BE.NMBS.008832375",
                            "locationX": "5.350226",
                            "locationY": "50.954841",
                            "@id": "http://irail.be/stations/NMBS/008832375",
                            "standardname": "Kiewit",
                            "name": "Kiewit"
                        },
                        "time": "1506346920",
                        "vehicle": "BE.NMBS.IC1512",
                        "platform": "2",
                        "platforminfo": {
                            "name": "2",
                            "normal": "1"
                        },
                        "canceled": "0",
                        "direction": {
                            "name": "Genk"
                        }
                    },
                    "duration": "7320",
                    "occupancy": {
                        "@id": "http://api.irail.be/terms/unknown",
                        "name": "unknown"
                    }
                },
                {
                    "id": "1",
                    "departure": {
                        "delay": "60",
                        "station": "Ghent-Sint-Pieters",
                        "stationinfo": {
                            "id": "BE.NMBS.008892007",
                            "locationX": "3.710675",
                            "locationY": "51.035896",
                            "@id": "http://irail.be/stations/NMBS/008892007",
                            "name": "Ghent-Sint-Pieters",
                            "standardname": "Gent-Sint-Pieters"
                        },
                        "time": "1506339600",
                        "vehicle": "BE.NMBS.IC2213",
                        "platform": "6",
                        "platforminfo": {
                            "name": "6",
                            "normal": "1"
                        },
                        "canceled": "0",
                        "direction": {
                            "name": "Tongeren"
                        },
                        "departureConnection": "http://irail.be/connections/8892007/20170925/IC2213",
                        "occupancy": {
                            "@id": "http://api.irail.be/terms/unknown",
                            "name": "unknown"
                        }
                    },
                    "arrival": {
                        "delay": "0",
                        "station": "Kiewit",
                        "stationinfo": {
                            "id": "BE.NMBS.008832375",
                            "locationX": "5.350226",
                            "locationY": "50.954841",
                            "@id": "http://irail.be/stations/NMBS/008832375",
                            "standardname": "Kiewit",
                            "name": "Kiewit"
                        },
                        "time": "1506349440",
                        "vehicle": "BE.NMBS.P2366",
                        "platform": "2",
                        "platforminfo": {
                            "name": "2",
                            "normal": "1"
                        },
                        "canceled": "0",
                        "direction": {
                            "name": "Genk"
                        }
                    },
                    "duration": "9840",
                    "vias": {
                        "number": "1",
                        "via": [
                            {
                                "id": "0",
                                "arrival": {
                                    "time": "1506347340",
                                    "platform": "2",
                                    "platforminfo": {
                                        "name": "2",
                                        "normal": "1"
                                    },
                                    "delay": "120",
                                    "canceled": "0",
                                    "direction": {
                                        "name": "Tongeren"
                                    },
                                    "vehicle": "BE.NMBS.IC2213",
                                    "departureConnection": "http://irail.be/connections/8831005/20170925/IC2213"
                                },
                                "departure": {
                                    "time": "1506348960",
                                    "platform": "8",
                                    "platforminfo": {
                                        "name": "8",
                                        "normal": "1"
                                    },
                                    "delay": "60",
                                    "canceled": "0",
                                    "direction": {
                                        "name": "Genk"
                                    },
                                    "vehicle": "BE.NMBS.P2366",
                                    "departureConnection": "http://irail.be/connections/8831005/20170925/P2366",
                                    "occupancy": {
                                        "@id": "http://api.irail.be/terms/unknown",
                                        "name": "unknown"
                                    }
                                },
                                "timeBetween": "1620",
                                "station": "Hasselt",
                                "stationinfo": {
                                    "id": "BE.NMBS.008831005",
                                    "locationX": "5.327627",
                                    "locationY": "50.930822",
                                    "@id": "http://irail.be/stations/NMBS/008831005",
                                    "standardname": "Hasselt",
                                    "name": "Hasselt"
                                },
                                "vehicle": "BE.NMBS.IC2213",
                                "direction": {
                                    "name": "Tongeren"
                                }
                            }
                        ]
                    }
                }]
            }

    + Attributes (ConnectionResponse)


+ Response 400 (application/json)
            
            {
                "error": 400,
                "message": "to not set. Please review your request and add the right parameters"
            }

+ Response 404 (application/json)

            {
                "error":404,
                "message": "Could not match 'query' with a station id in iRail. Please report this issue at https://github.com/irail/stations/issues/new if you think we should support your query."
            }

+ Response 500 (application/json)
            
            {
                "error": 500,
                "message": "Could not get data. Please report this issue at https://github.com/irail/irail/issues/new"
            }

+ Request XML
    
    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            <connections version="1.1" timestamp="1506352987">
                <connection id="0">
                    <departure delay="0" canceled="0">
                        <station id="BE.NMBS.008892007" locationX="3.710675" locationY="51.035896" URI="http://irail.be/stations/NMBS/008892007" standardname="Gent-Sint-Pieters">Ghent-Sint-Pieters</station>
                        <time formatted="2017-09-25T13:40:00">1506339600</time>
                        <vehicle>BE.NMBS.IC1512</vehicle>
                        <platform normal="1">11</platform>
                        <direction>Genk</direction>
                        <departureConnection>http://irail.be/connections/8892007/20170925/IC1512</departureConnection>
                        <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                    </departure>
                    <arrival delay="420" canceled="0">
                        <station id="BE.NMBS.008832375" locationX="5.350226" locationY="50.954841" URI="http://irail.be/stations/NMBS/008832375" standardname="Kiewit">Kiewit</station>
                        <time formatted="2017-09-25T15:42:00">1506346920</time>
                        <vehicle>BE.NMBS.IC1512</vehicle>
                        <platform normal="1">2</platform>
                        <direction>Genk</direction>
                    </arrival>
                    <duration>7320</duration>
                    <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                </connection>
                <connection id="1">
                    <departure delay="60" canceled="0">
                        <station id="BE.NMBS.008892007" locationX="3.710675" locationY="51.035896" URI="http://irail.be/stations/NMBS/008892007" standardname="Gent-Sint-Pieters">Ghent-Sint-Pieters</station>
                        <time formatted="2017-09-25T13:40:00">1506339600</time>
                        <vehicle>BE.NMBS.IC2213</vehicle>
                        <platform normal="1">6</platform>
                        <direction>Tongeren</direction>
                        <departureConnection>http://irail.be/connections/8892007/20170925/IC2213</departureConnection>
                        <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                    </departure>
                    <arrival delay="0" canceled="0">
                        <station id="BE.NMBS.008832375" locationX="5.350226" locationY="50.954841" URI="http://irail.be/stations/NMBS/008832375" standardname="Kiewit">Kiewit</station>
                        <time formatted="2017-09-25T16:24:00">1506349440</time>
                        <vehicle>BE.NMBS.P2366</vehicle>
                        <platform normal="1">2</platform>
                        <direction>Genk</direction>
                    </arrival>
                    <duration>9840</duration>
                    <vias number="1">
                        <via id="0">
                            <arrival delay="120" canceled="0">
                                <time formatted="2017-09-25T15:49:00">1506347340</time>
                                <platform normal="1">2</platform>
                                <direction>Tongeren</direction>
                                <vehicle>BE.NMBS.IC2213</vehicle>
                                <departureConnection>http://irail.be/connections/8831005/20170925/IC2213</departureConnection>
                            </arrival>
                            <departure delay="60" canceled="0">
                                <time formatted="2017-09-25T16:16:00">1506348960</time>
                                <platform normal="1">8</platform>
                                <direction>Genk</direction>
                                <vehicle>BE.NMBS.P2366</vehicle>
                                <departureConnection>http://irail.be/connections/8831005/20170925/P2366</departureConnection>
                                <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                            </departure>
                            <timeBetween>1620</timeBetween>
                            <station id="BE.NMBS.008831005" locationX="5.327627" locationY="50.930822" URI="http://irail.be/stations/NMBS/008831005"             standardname="Hasselt">Hasselt</station>
                            <vehicle>BE.NMBS.IC2213</vehicle>
                            <direction>Tongeren</direction>
                        </via>
                    </vias>
                    <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                </connection>
            </connections>



+ Response 404 (application/xml)

    + Body
           
            <error code="404">Could not match "samplestation" with a station id in iRail. Please report this issue at https://github.com/irail/stations/issues/new if you think we should support your query.</error>