# Group Disturbances

Retrieve information about current disturbances.

## Disturbance API [/disturbances/{?format,lineBreakCharacter,lang}]

+ Parameters
    + lineBreakCharacter: '' (string, optional) - The character to use for line breaks. By default these are removed to create a continuous text without special characters,
    but you may provide a linebreak character sequence here to get line breaks which are compatible with your client. Examples are <br/> and \n.
        + Default: ''

    <!-- include(fragments/parameters_format.apib) -->

    <!-- include(fragments/parameters_lang.apib) -->


### Retrieve the current disturbances [GET]

::: note
As of November 2017, additional measures have been taken to improve reliability of this endpoint, even if the original NMBS RSS feed is not available. During short RSS or NMBS website outages, this endpoint should keep providing the last known status.
:::

Retrieve information about the current disturbances on the rail network. This data is sourced from the NMBS RSS feed, cleaned up and properly formatted. If a link (to a website) or attachment (link to a file) is detected will this be returned through the link and attachment fields.
You can distinguish between scheduled changes (works) and unscheduled issues (disturbances) based on the type field.

+ Request Json

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: "*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            {
              "version": "1.1",
              "timestamp": "1581853952",
              "disturbance": [
                {
                  "id": "0",
                  "title": "Brux.-Midi/Brus.-Zuid - Amsterdam CS (NL): Incident on the Dutch rail network.",
                  "description": "Between Brux.-Midi/Brus.-Zuid and Amsterdam CS (NL): Delays and cancellations are possible. Between Rotterdam CS (NL) and Amsterdam CS (NL): Disrupted train traffic. Indefinite duration of the failure. Listen to the announcements, consult the automatic departure boards or plan your trip via the SNCB app or sncb.be for more information.",
                  "link": "http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41188&channelFilter=custom2,livemap,rss_line_10,twitter,custom1,timetable&",
                  "type": "disturbance",
                  "timestamp": "1581853724"
                },
                {
                  "id": "1",
                  "title": "Soignies / Zinnik: Failure of a level crossing.",
                  "description": "Delays between 5 and 15 minutes are possible in both directions. Indefinite duration of the failure. Listen to the announcements, consult the automatic departure boards or plan your trip via the SNCB app or sncb.be for more information.",
                  "link": "http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41187&channelFilter=custom2,livemap,rss_line_10,twitter,custom1,timetable&",
                  "type": "disturbance",
                  "timestamp": "1581849358"
                },
                {
                  "id": "2",
                  "title": "Storm warning.",
                  "description": "On entire network, from saturday 15/02 evening to sunday 16/02 : Delays and cancellations are possible. Listen to the announcements, consult the automatic departure boards or plan your trip via the SNCB app or sncb.be for more information.",
                  "link": "http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41174&channelFilter=timetable,custom1,twitter,rss_line_10,livemap,custom2&",
                  "type": "disturbance",
                  "timestamp": "1581767543"
                },
                {
                  "id": "3",
                  "title": "Brux.-Nord/Brus.-Noord - Schaerbeek / Schaarbeek",
                  "description": "We are conducting work for you between Brux.-Nord/Brus.-Noord and Schaerbeek / Schaarbeek. Detailed information only available in French (FR) and in Dutch (NL).",
                  "link": "http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=works&messageID=41159&channelFilter=rss_line_90&",
                  "type": "planned",
                  "timestamp": "1581691640",
                  "attachment": "http://www.belgianrail.be/jp/download/brail_him/1581691545283_NL-03003S.pdf"
                },
                {
                  "id": "4",
                  "title": "Ostende / Oostende - Anvers-Central / Antwerpen-Centraal",
                  "description": "We are conducting work for you between Ostende / Oostende and Anvers-Central / Antwerpen-Centraal. Detailed information only available in French (FR) and in Dutch (NL).",
                  "link": "http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=works&messageID=40825&channelFilter=timetable,rss_line_90,custom2&",
                  "type": "planned",
                  "timestamp": "1581691528",
                  "attachment": "http://www.belgianrail.be/jp/download/brail_him/1580998838767_NL-02045S.pdf"
                }
              ]
            }

+ Request XML

    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

    + Headers

            Access-Control-Allow-Origin: "*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            
            <disturbances version="1.1" timestamp="1581854029">
                <disturbance id="0">
                    <title>Soignies / Zinnik: Failure of a level crossing.</title>
                    <description><![CDATA[The trains are running normally again.]]></description>
                    <link>
                        <![CDATA[http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41187&channelFilter=custom2,livemap,rss_line_10,twitter,custom1,timetable&]]></link>
                    <type>disturbance</type>
                    <timestamp>1581853971</timestamp>
                </disturbance>
                <disturbance id="1">
                    <title>Brux.-Midi/Brus.-Zuid - Amsterdam CS (NL): Incident on the Dutch rail network.</title>
                    <description>
                        <![CDATA[Between Brux.-Midi/Brus.-Zuid and Amsterdam CS (NL): Delays and cancellations are possible. Between Rotterdam CS (NL) and Amsterdam CS (NL): Disrupted train traffic. Indefinite duration of the failure. Listen to the announcements, consult the automatic departure boards or plan your trip via the SNCB app or sncb.be for more information.]]></description>
                    <link>
                        <![CDATA[http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41188&channelFilter=custom2,livemap,rss_line_10,twitter,custom1,timetable&]]></link>
                    <type>disturbance</type>
                    <timestamp>1581853724</timestamp>
                </disturbance>
                <disturbance id="2">
                    <title>Storm warning.</title>
                    <description>
                        <![CDATA[On entire network, from saturday 15/02 evening to sunday 16/02 : Delays and cancellations are possible. Listen to the announcements, consult the automatic departure boards or plan your trip via the SNCB app or sncb.be for more information.]]></description>
                    <link>
                        <![CDATA[http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=trouble&messageID=41174&channelFilter=timetable,custom1,twitter,rss_line_10,livemap,custom2&]]></link>
                    <type>disturbance</type>
                    <timestamp>1581767543</timestamp>
                </disturbance>
                <disturbance id="3">
                    <title>Brux.-Nord/Brus.-Noord - Schaerbeek / Schaarbeek</title>
                    <description>
                        <![CDATA[We are conducting work for you between Brux.-Nord/Brus.-Noord and Schaerbeek / Schaarbeek. Detailed information only available in French (FR) and in Dutch (NL).]]></description>
                    <link>
                        <![CDATA[http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=works&messageID=41159&channelFilter=rss_line_90&]]></link>
                    <type>planned</type>
                    <timestamp>1581691640</timestamp>
                    <attachment>http://www.belgianrail.be/jp/download/brail_him/1581691545283_NL-03003S.pdf</attachment>
                </disturbance>
                <disturbance id="4">
                    <title>Ostende / Oostende - Anvers-Central / Antwerpen-Centraal</title>
                    <description>
                        <![CDATA[We are conducting work for you between Ostende / Oostende and Anvers-Central / Antwerpen-Centraal. Detailed information only available in French (FR) and in Dutch (NL).]]></description>
                    <link>
                        <![CDATA[http://www.belgianrail.be/jp/nmbs-realtime/help.exe/en?tpl=showmap_external&tplParamHimMsgInfoGroup=works&messageID=40825&channelFilter=timetable,rss_line_90,custom2&]]></link>
                    <type>planned</type>
                    <timestamp>1581691528</timestamp>
                    <attachment>http://www.belgianrail.be/jp/download/brail_him/1580998838767_NL-02045S.pdf</attachment>
                </disturbance>
            </disturbances>