FORMAT: 1A

# iRail

iRail supports digital creativity concerning mobility in Belgium. 
This is an attempt to make the railway time schedules in Belgium easily available for anyone.

The iRail api allows anyone to query trains, stations, liveboards and connections.

<!-- include(stations.apib) -->
<!-- include(liveboard.apib) -->
<!-- include(connections.apib) -->
<!-- include(vehicle.apib) -->

