# Group Stations

Retrieve a list of all stations.
Alternatively, you can check out our repo at https://github.com/iRail/stations for a CSV of all stations, and nodejs scripts to convert this CSV to other formats.

## Stations API [/stations/{?format,lang}]

+ Parameters

    <!-- include(fragments/parameters_format.apib) -->

    <!-- include(fragments/parameters_lang.apib) -->

### Retrieve all stations [GET]

+ Request Json

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            {
                "version": "1.1",
                "timestamp": "1489621486",
                "station": [
                    {
                        "id": "BE.NMBS.007015400",
                        "locationX": "-0.1260606",
                        "locationY": "51.5310399",
                        "@id": "http://irail.be/stations/NMBS/007015400",
                        "standardname": "London Saint Pancras International",
                        "name": "London Saint Pancras International"
                    }
                ]
            }

    + Attributes (StationResponse)

+ Request XML
    
    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

    + Headers

            Access-Control-Allow-Origin:"*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            <stations version="1.1" timestamp="1489621390">
               <station id="BE.NMBS.007015400" locationX="-0.1260606" locationY="51.5310399" URI="http://irail.be/stations/NMBS/007015400" standardname="London Saint Pancras International">London Saint Pancras International</station>
            </stations>
