# Group Vehicle

Retrieve information about a vehicle.

## Vehicle API [/vehicle/{?id,fast,format,lang,alerts}]

+ Parameters

    + id: `BE.NMBS.IC1832` (string, required): The id of the vehicle to query. The identifier 'BE.NMBS.' can be left out, but is encouraged to ensure your application is future-proof.

    + alerts: `false`(boolean, optional) - Wether or not to include alerts about a train in the response. This could be railworks etc, announced on the NMBS website.

    <!-- include(fragments/parameters_format.apib) -->

    <!-- include(fragments/parameters_lang.apib) -->

    <!-- include(fragments/parameters_fast.apib) -->

### Retrieve a vehicle [GET]

Retrieve information about a vehicle (train), including stops, occupancy, current location and delays.

+ Request Json

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: "*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            {
                "version": "1.1",
                "timestamp": "1489621902",
                "vehicle": "BE.NMBS.IC3033",
                "vehicleinfo": {
                    "locationX": "3.216726",
                    "locationY": "51.197226",
                    "name": "BE.NMBS.IC3033",
                    "shortname": "IC3033",
                    "@id": "http://irail.be/vehicle/IC3033"
                },
                "stops": {
                    "number": "10",
                    "stop": [
                        {
                            "id": "0",
                            "station": "Antwerp-Central",
                            "stationinfo": {
                                "id": "BE.NMBS.008821006",
                                "locationX": "4.421101",
                                "locationY": "51.2172",
                                "@id": "http://irail.be/stations/NMBS/008821006",
                                "name": "Antwerp-Central",
                                "standardname": "Antwerpen-Centraal"
                            },
                            "time": "1505984760",
                            "delay": "240",
                            "platform": "1",
                            "platforminfo": {
                                "name": "1",
                                "normal": "1"
                            },
                            "canceled": "0",
                            "departureDelay": "240",
                            "departureCanceled": "0",
                            "scheduledDepartureTime": "1505984760",
                            "scheduledArrivalTime": "1505984760",
                            "arrivalDelay": "0",
                            "arrivalCanceled": "0",
                            "departureConnection": "http://irail.be/connections/8821006/20170921/IC3033",
                            "left": "1",
                            "occupancy": {
                                "@id": "http://api.irail.be/terms/unknown",
                                "name": "unknown"
                            }                            
                        }
                    ]            
                }
            }

    + Attributes (VehicleResponse)

+ Response 404 (application/json)

    + Body
           
            {
                "error": 404,
                "message": "Route not available."
            }

+ Request XML

    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

    + Headers

            Access-Control-Allow-Origin: "*"
            cache-control: Public
            etag: "e5e7c8ae25bb71cdfce80412c2b1be54"

    + Body

            <vehicleinformation version="1.1" timestamp="1505995100">
                <vehicle locationX="3.216726" locationY="51.197226" shortname="IC1832" URI="http://irail.be/vehicle/IC1832">BE.NMBS.IC1832</vehicle>
                <stops number="10">
                    <stop id="0" delay="240" canceled="0" left="1">
                        <station id="BE.NMBS.008821006" locationX="4.421101" locationY="51.2172" URI="http://irail.be/stations/NMBS/008821006" standardname="Antwerpen-Centraal">Antwerp-Central</station>
                        <time formatted="2017-09-21T11:06:00">1505984760</time>
                        <platform normal="1">1</platform>
                        <departureDelay>240</departureDelay>
                        <departureCanceled>0</departureCanceled>
                        <scheduledDepartureTime formatted="2017-09-21T11:06:00">1505984760</scheduledDepartureTime>
                        <scheduledArrivalTime formatted="2017-09-21T11:06:00">1505984760</scheduledArrivalTime>
                        <arrivalDelay>0</arrivalDelay>
                        <arrivalCanceled>0</arrivalCanceled>
                        <departureConnection>http://irail.be/connections/8821006/20170921/IC1832</departureConnection>
                        <occupancy URI="http://api.irail.be/terms/unknown">unknown</occupancy>
                    </stop>
                </stops>    
            </vehicleinformation>    


+ Response 404 (application/xml)

    + Body
           
            <error code="404">Route not available.</error>

